swagger: '2.0'
info:
  $ref: info/index.yaml
securityDefinitions:
  UserSecurity:
    type: apiKey
    in: header
    name: Authorization
security:
  - UserSecurity: []
schemes:
  - http
basePath: '/api'
produces:  
  - application/json
consumes:
  - application/json
paths:
  $ref: paths/index.yaml
definitions:
  $ref: definitions/index.yaml
  

